# -*- coding: utf-8 -*-
"""CLASIFICACION_SUELOS_2_curvas_ dario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eo9Oi1o4TmtlJMofphVqsNMF5Q1H3FxN

#**Programacion 2**
#Clasificacion de suelos
## Jessica Ayslin lagos Amaya
### Cod. 20211579054
"""

import math

tamizN200=int(input('Ingrese el % pasa tamiz N° 200 :'))
if tamizN200 >=50:
  LL=int(input('Ingrese el limite liquido: '))
  IP=int(input('ingrese el indice de plasticidad: '))
else:
   tamizN4=int(input('ingrese el % pasa tamiz  N°4: '))
   Cu=int(input('ingrese el coheficiente de uniformidad: '))
   Cc=int(input('ingrese el coheficiente de curvatura: '))
   Ip=int(input('ingrese el indice de plasticidad'))

#colocar todas las funciones para acortar codigo 
def arenaslimpias():
  if  Cu >=6  and 1 <= Cc <= 3: 
    print('SW - Arena bien graduada')
  elif Cu < 6 and 1 > Cc > 3: 
    print('SP - Arena mal graduada')
  else:
    print('datos erroneos, revise')

def arenaslimpiasconfinos():
  if (Cu >= 6 and 1 <= Cc <= 3) and Ip <  4: 
      print ('SW - SM  : Arena  bien graduada con limo')
  elif  (Cu >= 6 and 1 <= Cc <= 3) and Ip > 7 :
      print ('SW - SC  : Arena  bien graduada con arcilla')
  elif (Cu < 6 and 1 > Cc > 3) and Ip <  4 : 
      print ('SP - SM  : Arena  mal graduada con limo')
  elif (Cu < 6 and 1 > Cc > 3) and Ip > 7 :
      print( 'SP - SC : Arena mal graduada con arcilla')

def arenasconfinos():
  if Ip <  4 or Ip < [0.73 * (LL-20)]:
    print ('SM - Arena limosa')
  elif Ip > 7 or [0.9 * (LL-8)]> Ip [0.73 * (LL-20)]:
    print( 'SC - Arena arcillosa')
  else:
      print('datos errones , revise')
              
def gravaslimpias():
  if  Cu >= 4 and 1 <= Cc <= 3: 
    print('GW - Grava bien graduada')
  elif Cu < 4 and 1 > Cc > 3: 
    print('GP - Grava mal graduada')
  else:
   print('datos erroneos, revise')

def gravaslimpiasconfinos():
  if (Cu >= 4 and 1 <= Cc <= 3) and Ip <  4: 
    print ('GW - GM  : Grava  bien graduada con limo')
  elif  (Cu >= 4 and 1 <= Cc <= 3) and Ip > 7 :
    print ('GW - GC  : Grava  bien graduada con arcilla')
  elif (Cu < 4 and 1 > Cc > 3) and Ip <  4 : 
    print ('GP - GM  : Grava  mal graduada con limo')
  elif (Cu < 4 and 1 > Cc > 3) and Ip > 7 :
    print( 'GP - GC : Grava mal graduada con arcilla')

def gravasconfinos():
 if Ip <  4 or Ip < [0.73 * (LL-20)]:
    print ('GM - Grava limosa')
 elif Ip > 7 or [0.9 * (LL-8)]> Ip [0.73 * (LL-20)]:
    print( 'GC - grava arcillosa')
 else:
    print('datos errones , revise')


 if tamizN200 >= 50: #El 50% o mas pasa la malla N°200 son suelos finos
    print ("El suelo es de particulas finas")
    
    if LL >= 50: 

        if IP > 7 and [0.9 * (LL-8)]> Ip [0.73 * (LL-20)]:
            print ("SUELO INORGANICO - CH - arcilla de alta plasticidad")

        elif IP < 4 and  Ip < [0.73 * (LL-20)]:
            print ("SUELO INORGANICO - MH - limo de alta plasticidad")
        else:
            print ("no existe")

    elif  LL < 50: 

        if IP >7 and [0.9 * (LL-8)]> Ip [0.73 * (LL-20)]:
           print ("SUELO INORGANICO -CL - arcilla de baja plasticidad")
 
        elif IP < 4 and  Ip < [0.73 * (LL-20)]:
           print ("SUELO INORGANICO -ML - limo de baja plasticidad")
        else:
           print ("no existe")
           

     
 else: #El 50% no pasa la malla N°200 son suelos gruesos
    print ( "El suelo es de particulas gruesas")

    if  tamizN4 >= 50:  #El 50% o mas pasa la malla N°4 es una arena
             print('arena')

             if tamizN200 < 5 :
               print('Arenas limpias')
               
               arenaslimpias()
             
             elif 5 < tamizN200 and tamizN200 < 12 :
               print('Arenas limpias con finos')

               arenaslimpiasconfinos()
                         
             else:
              print('Arenas con finos')

              arenasconfinos()
             

    else:  #El 50% no pasa la malla N°4 es una grava
               print('grava')

               if tamizN200 < 5 :
                print('Gravas limpias') 
                
                gravaslimpias()


               elif 5 < tamizN200 and tamizN200 < 12 :
                print('Gravas limpias con finos')

                gravaslimpiasconfinos()
                   
                            
               else:
                print('Gravas con finos')

                gravasconfinos()


if tamizN200 >= 50: #El 50% o mas pasa la malla N°200 son suelos finos
    print ("El suelo es de particulas finas- carta de plasticidad")



